// Maps each country route to its display metadata, hero image, flag, and the
// JSON data file (metadata + faqs) used by CountryPage.
//
// Country JSON files only carry `metadata` + `faqs`; the rest of the page is
// generated by CountryPage from this config + the service type.

export interface CountryFaqs {
  title: string
  subtitle: string
  items: { question: string; answer: string }[]
}

export interface CountryData {
  metadata: {
    title: string
    description: string
    keywords?: string[]
  }
  faqs: CountryFaqs
}

export type ServiceType = 'eor' | 'contractor'

export interface CountryConfig {
  /** Display name, e.g. "The Netherlands" */
  name: string
  /** EOR or Contractor management */
  type: ServiceType
  /** Hero image under /public */
  image: string
  /** Flag image under /public */
  flag: string
  /** Key into the JSON map (filename without extension) */
  dataKey: string
}

// Explicit imports replacing import.meta.glob (Vite-specific)
import belgiumEor from './belgium-eor.json'
import belgiumContractor from './belgium-contractor.json'
import chinaEor from './china-eor.json'
import czechEor from './czech-republic-eor.json'
import czechContractor from './czech-republic-contractor.json'
import franceEor from './france-eor.json'
import franceContractor from './france-contractor.json'
import germanyEor from './germany-eor.json'
import germanyContractor from './germany-contractor.json'
import hongKongEor from './hong-kong-eor.json'
import indiaEor from './india-eor.json'
import indiaContractor from './india-contractor.json'
import italyEor from './italy-eor.json'
import italyContractor from './italy-contractor.json'
import netherlandsEor from './netherlands-eor.json'
import netherlandsContractor from './netherlands-contractor.json'
import polandEor from './poland-eor.json'
import polandContractor from './poland-contractor.json'
import spainEor from './spain-eor.json'
import spainContractor from './spain-contractor.json'
import uaeEor from './uae-eor.json'
import uaeContractor from './uae-contractor.json'
import ukEor from './united-kingdom-eor.json'
import ukContractor from './united-kingdom-contractor.json'

const allJson: Record<string, CountryData> = {
  'belgium-eor': belgiumEor as CountryData,
  'belgium-contractor': belgiumContractor as CountryData,
  'china-eor': chinaEor as CountryData,
  'czech-republic-eor': czechEor as CountryData,
  'czech-republic-contractor': czechContractor as CountryData,
  'france-eor': franceEor as CountryData,
  'france-contractor': franceContractor as CountryData,
  'germany-eor': germanyEor as CountryData,
  'germany-contractor': germanyContractor as CountryData,
  'hong-kong-eor': hongKongEor as CountryData,
  'india-eor': indiaEor as CountryData,
  'india-contractor': indiaContractor as CountryData,
  'italy-eor': italyEor as CountryData,
  'italy-contractor': italyContractor as CountryData,
  'netherlands-eor': netherlandsEor as CountryData,
  'netherlands-contractor': netherlandsContractor as CountryData,
  'poland-eor': polandEor as CountryData,
  'poland-contractor': polandContractor as CountryData,
  'spain-eor': spainEor as CountryData,
  'spain-contractor': spainContractor as CountryData,
  'uae-eor': uaeEor as CountryData,
  'uae-contractor': uaeContractor as CountryData,
  'united-kingdom-eor': ukEor as CountryData,
  'united-kingdom-contractor': ukContractor as CountryData,
}

export function loadCountryData(dataKey: string): CountryData | null {
  return allJson[dataKey] ?? null
}

const FLAG: Record<string, string> = {
  belgium: '/countries/flag/Flag_of_Belgium.svg.png',
  china: "/countries/flag/Flag_of_the_People's_Republic_of_China.svg.webp",
  'czech-republic': '/countries/flag/Flag_of_the_Czech_Republic.svg.webp',
  france: '/countries/flag/Flag_of_France.svg.webp',
  germany: '/countries/flag/Flag_of_Germany_(3-2).svg.png',
  'hong-kong': '/countries/flag/Flag_of_Hong_Kong.svg (1).png',
  india: '/countries/flag/Flag_of_India.svg.webp',
  italy: '/countries/flag/Flag_of_Italy.svg.png',
  netherlands: '/countries/flag/Flag_of_the_Netherlands.svg.webp',
  poland: '/countries/flag/Flag_of_Poland.svg.png',
  spain: '/countries/flag/Flag_of_Spain.svg.png',
  uae: '/countries/flag/Flag_of_the_United_Arab_Emirates.svg',
  'united-kingdom': '/countries/flag/Flag-United-Kingdom.webp',
}

// EOR hero image slug differs from route slug in a few cases.
const EOR_IMG: Record<string, string> = {
  netherlands: 'eor-netherlands',
  india: 'eor-india',
  poland: 'eor-poland',
  'united-kingdom': 'eor-uk',
  germany: 'eor-germany',
  italy: 'eor-Italy',
  'czech-republic': 'eor-czech',
  france: 'eor-france',
  belgium: 'eor-belgium',
  spain: 'eor-spain',
  uae: 'eor-uae',
  'hong-kong': 'eor-hong-kong',
  china: 'eor-china',
}
const CONTRACTOR_IMG: Record<string, string> = {
  netherlands: 'contractor-netherlands',
  india: 'contractor-india',
  poland: 'contractor-poland',
  'united-kingdom': 'contractor-uk',
  germany: 'contractor-germany',
  italy: 'contractor-italy',
  'czech-republic': 'contractor-czec-republic',
  france: 'contractor-france',
  belgium: 'contractor-belgium',
  spain: 'contractor-spain',
  uae: 'contractor-uae',
}

function eorEntry(slug: string, name: string): CountryConfig {
  return {
    name,
    type: 'eor',
    image: `/countries/${EOR_IMG[slug]}.webp`,
    flag: FLAG[slug],
    dataKey: `${slug}-eor`,
  }
}
function contractorEntry(slug: string, name: string): CountryConfig {
  return {
    name,
    type: 'contractor',
    image: `/countries/${CONTRACTOR_IMG[slug]}.webp`,
    flag: FLAG[slug],
    dataKey: `${slug}-contractor`,
  }
}

// Route path → config. Keyed by the path the router uses.
export const COUNTRY_CONFIG: Record<string, CountryConfig> = {
  '/belgium': eorEntry('belgium', 'Belgium'),
  '/belgium-contractor': contractorEntry('belgium', 'Belgium'),
  '/china': eorEntry('china', 'China'),
  '/czech-republic': eorEntry('czech-republic', 'Czech Republic'),
  '/czech-republic-contractor': contractorEntry('czech-republic', 'Czech Republic'),
  '/france': eorEntry('france', 'France'),
  '/france-contractor': contractorEntry('france', 'France'),
  '/germany': eorEntry('germany', 'Germany'),
  '/germany-contractor': contractorEntry('germany', 'Germany'),
  '/hong-kong': eorEntry('hong-kong', 'Hong Kong'),
  '/india': eorEntry('india', 'India'),
  '/india-contractor': contractorEntry('india', 'India'),
  '/italy': eorEntry('italy', 'Italy'),
  '/italy-contractor': contractorEntry('italy', 'Italy'),
  '/netherlands': eorEntry('netherlands', 'The Netherlands'),
  '/netherlands-contractor': contractorEntry('netherlands', 'The Netherlands'),
  '/poland': eorEntry('poland', 'Poland'),
  '/poland-contractor': contractorEntry('poland', 'Poland'),
  '/spain': eorEntry('spain', 'Spain'),
  '/spain-contractor': contractorEntry('spain', 'Spain'),
  '/uae': eorEntry('uae', 'UAE'),
  '/uae-contractor': contractorEntry('uae', 'UAE'),
  '/united-kingdom': eorEntry('united-kingdom', 'United Kingdom'),
  '/united-kingdom-contractor': contractorEntry('united-kingdom', 'United Kingdom'),
}
